branches:
  only:
    - master

platform:
  - x64

matrix:
  - "PYTHON=C:\\Python36-x64"

install:
  - "SET PATH=%PYTHON%;%PATH%"
  - "python --version"
  - "python -m pip install --upgrade pip"
  - "python -m pip install -e .[ci,pack,tests]"

build_script:
  - "python -m invoke pack"

test_script:
  # Shorten paths, workaround https://bugs.python.org/issue18199
  - "subst T: %TEMP%"
  - "set TEMP=T:\\"
  - "set TMP=T:\\"
  - "python -m pytest -v -n 8 tests"

artifacts:
- path: ".\\pack\\passa.zip"
